# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52f552ce7f47c373b8e4c6dbdf6e9d99952c771b7911180487db87439a774b8b375e9d52c3a60d866e79d4b1854adc8d0c5d8b6cda5fdcc93bcfe0001e1fd871

test:
  secret_key_base: 3282cb083e1e84df69dc3595eeba4b8d54c96aea5d0c28be503e53d5383da324b26fd60938454eca99e5c7b6c9e6c40b806852f3b77e073a7099544838b3f9b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
